// Gabriel Mosz All Rights Reserved

#pragma once

#include "NativeGameplayTags.h"

namespace VarvaraGameplayTags
{
	/* Input Tags */
	VARVARAA_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Move)
	VARVARAA_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Look)
	VARVARAA_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Focus)
	VARVARAA_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_EquipAxe)
	VARVARAA_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_UnequipAxe)

	/* Weapon Tags */
	VARVARAA_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Weapon_Axe)
	VARVARAA_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Weapon_Torch)

	/* Event Tags */
	VARVARAA_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Event_EquipAxe)
	VARVARAA_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Event_UnequipAxe)

	/* Ability Tags*/
	VARVARAA_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_EquipAxe)
	VARVARAA_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_UnequipAxe)
}
